### ISSUE TITLE
Revue mi-projet

### ISSUE THREAD

**Issue by SpicyPaper** [HE-Arc/AnalyChess#13]
Pourquoi avoir changé les guillemets tout à coup ? :)
https://github.com/HE-Arc/AnalyChess/blob/fa52fa52c566eb9d7425ab7951bbd481c11281c0/analychess/analychess/urls.py#L28

Mettez de l'ordre dans vos imports
https://github.com/HE-Arc/AnalyChess/blob/fa52fa52c566eb9d7425ab7951bbd481c11281c0/analychess/analychess/urls.py#L16-L24

Pourquoi avoir mit ces imports plus bas ? Regroupez les imports ne serait-il pas plus judicieux et plus logique ?
https://github.com/HE-Arc/AnalyChess/blob/fa52fa52c566eb9d7425ab7951bbd481c11281c0/analychess/api/models.py#L14-L17

Si ce n'est pas vous qui écrivez quelque chose une bonne pratique est de mettre les sources, ça vous permettra de retrouver l'info en cas de besoin et pour les autres de comprendre pourquoi et comment quelque chose à été fait :
https://www.django-rest-framework.org/api-guide/permissions/#examples
https://github.com/HE-Arc/AnalyChess/blob/fa52fa52c566eb9d7425ab7951bbd481c11281c0/analychess/api/permissions.py#L4-L16

Si jamais le DRF met à dispo des outils pas mal. p.ex. ici vous pourriez rajouter le champ 'url' et cela vous permetterait de naviguer plus simplement dans la browsable API du DRF.
https://github.com/HE-Arc/AnalyChess/blob/fa52fa52c566eb9d7425ab7951bbd481c11281c0/analychess/api/serializers.py#L10

Je vous recommande de lire le chapitre sur les ViewSets du DRF qui permet de faire beaucoup de trucs cool pour vous. Par exemple dans vos views vous pourriez avoir une viewset pour le User et une autre pour le Game à la place de découper comme vous l'avez fait pour l'instant. C'est plus logique, c'est fait pour vous et c'est plus propre. Cela vous permet également de simplifier vos urls en utilisant les routers du DRF. Je vous laisse checker tout ça :
https://www.django-rest-framework.org/api-guide/viewsets/
https://www.django-rest-framework.org/api-guide/routers/
https://github.com/HE-Arc/AnalyChess/blob/fa52fa52c566eb9d7425ab7951bbd481c11281c0/analychess/api/views.py#L19-L35

Aie... j'espère que c'est temporaire :) Parce que si vous souhaitez faire un truc du genre vous pouvez utiliser les v-for fournit par VueJS
https://github.com/HE-Arc/AnalyChess/blob/fa52fa52c566eb9d7425ab7951bbd481c11281c0/analychess_front/src/views/Account.vue#L9-L16

**Comment by chichha** [comment]
@SpicyPaper 
Tout a été modifié / corrigé
